---
- hosts: tonos
  gather_facts: false

  vars:
    remote_config_path: /repos/{{ remote_config_repo_name }}.git

  tasks:
  - name: Get git-shell path
    changed_when: false
    shell: which git-shell
    register: git_shell
    tags: git

  - name: Create git group
    become: true
    group:
      name: git
      system: true
    tags: git

  - name: Create git user
    become: true
    user:
      name: git
      group: git
      system: true
      password_lock: true
      shell: "{{ git_shell.stdout }}"
    tags: git

  - name: Append public key to known_hosts
    become: true
    authorized_key:
      user: git
      key: "{{ lookup('file', git_ssh_id_path + '.pub') }}"
    tags:
    - git
    - git-authorized-keys

  - name: Create git repos storage
    become: true
    file:
      name: /srv/git
      state: directory
      owner: git
      group: git
    tags:
    - git
    - git-repos

  - name: Create git repos storage link
    become: true
    file:
      name: /repos
      src: /srv/git
      state: link
    tags:
    - git
    - git-repos

  - name: Create git repos paths
    become: true
    become_user: git
    file:
      name: "{{ remote_config_path }}"
      state: directory
      mode: u=xrw,g=xr,o=x
    tags:
    - git
    - git-repos

  - name: Initialize git repo
    become: true
    become_user: git
    changed_when: false
    command: git init --bare
    args:
      chdir: /repos/{{ remote_config_repo_name }}.git
    tags:
    - git
    - git-repos
