---
- name: Ensure system up-to-date
  import_playbook: ubuntu/upgrade-system.yml

- name: Ensure base configuration complete
  import_playbook: ubuntu/bootstrap-base.yml

- name: Ensure docker-engine environment ready
  import_playbook: ubuntu/bootstrap-docker.yml
