version: '2.2'

services:

  node:
    image: amttr/tonos-ton-node
    restart: unless-stopped
    environment:
      ADNL_PORT:
      VALIDATOR_NAME:
      NETWORK_TYPE:
      CONFIGS_PATH:
      STATSD_DOMAIN:
      STATSD_PORT:
      STAKE:
      MSIG_ENABLE:
      SDK_URL:
    ports:
      - "${ADNL_PORT}:${ADNL_PORT}/udp"
    networks:
      - proxy_nw
    volumes:
      - ./configs/:/ton-node/configs/
      - ./logs/:/ton-node/logs/
      - DB:/ton-node/node_db/
      - /tmp/metrics/:/tmp/metrics/
    command: ["normal"]
    mem_limit: "${MEM_LIMIT}"
    logging:
      driver: json-file
      options:
        max-size: "1000m"
        max-file: "100"

networks:
  proxy_nw:
    external: true
volumes:
  DB:
